table transacoes
	lineageTag: 92d85646-5559-4100-9fed-ed22ae2137a1

	measure 'Valor Total' = SUM(transacoes[Total])
		displayFolder: Medidas
		lineageTag: 8b5dd18e-56fe-4a83-9fbe-5b237ab1f6bd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cotação corrigida' = ```
			
			
			VAR __DataCtx = MAX(calendario[Data]) 
			
			VAR __UltimaDataComCotacao = 
			    CALCULATE(
			        LASTNONBLANK(calendario[Data], [Cotação do dia]),
			        calendario[Data] <= __DataCtx
			    )
			
			RETURN
			    CALCULATE(
			        [Cotação do dia],
			        calendario[Data] = __UltimaDataComCotacao
			    )
			
			```
		displayFolder: Medidas
		lineageTag: f651f27d-f526-4ea9-9ac2-7adca0616026

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total R$' = ```
			
			SUMX(
			    moedas,
			    SUMX(
			        calendario,
			        COALESCE([Cotação corrigida], 1) * [Valor Total] 
			    )
			) 
			```
		displayFolder: Medidas
		lineageTag: 4b8f6d51-a2d6-41ed-84f1-a242326883b8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ID
		dataType: double
		displayFolder: Colunas
		lineageTag: d49def13-b280-491d-bbde-67bb20667c94
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Data
		dataType: dateTime
		formatString: dd/mm/yy
		displayFolder: Colunas
		lineageTag: 74d9dab9-e65e-4ab2-96de-f7967a1cc345
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Total
		dataType: double
		displayFolder: Colunas
		lineageTag: 8c9b1be6-eef2-4b00-830d-e82bda84db3f
		summarizeBy: sum
		sourceColumn: Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Moeda
		dataType: string
		displayFolder: Colunas
		lineageTag: 19453069-a1b0-4fdd-b0d5-3857de3c773a
		summarizeBy: none
		sourceColumn: Moeda

		annotation SummarizationSetBy = Automatic

	partition transacoes = m
		mode: import
		queryGroup: Fatos
		source = ```
				let
				    source = Excel.Workbook(
				        File.Contents(base_transacoes), 
				        true, 
				        null
				    ),
				    
				    transacoes_Table = source{[Item="transacoes",Kind="Table"]}[Data],
				    
				    datesRestricted = Table.SelectRows(
				        transacoes_Table, 
				        each [Data] >= data_inicial and [Data] <= data_final
				    )
				in
				    datesRestricted
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

